name: linting, testing, building
run-name: ${{ github.actor }} 🚀

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deps-installation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: yarn installation
        run: npm install -g yarn
      - name: Cache npm dependencies
        uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn-lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: dependencies installation
        run: yarn
  #  @todo разобраться с Error [ERR_REQUIRE_ESM]: require() of ES Module
  #  linting:
  #    runs-on: ubuntu-latest
  #    strategy:
  #      matrix:
  #        node-version: [18.x]
  #    needs: [deps-installation]
  #    steps:
  #      - name: Checkout Commit
  #        uses: actions/checkout@v4
  #      - name: Setup Node.js ${{ matrix.node-version }}
  #        uses: actions/setup-node@v4
  #        with:
  #          node-version: ${{ matrix.node }}
  #      - name: restoring dependencies
  #        uses: actions/cache@v4
  #        id: cache-dependencies
  #        with:
  #          path: node_modules
  #          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn-lock') }}
  #          restore-keys: |
  #            ${{ runner.os }}-node-
  #      - name: linting
  #        run: yarn cache clean && yarn lint
  production-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    needs: [deps-installation]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: restoring dependencies
        uses: actions/checkout@v4
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn-lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: project building
        run: yarn build
